// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw136LW-yxliGlZZ56R9JZgZmuF1Lg9a0',
    appId: '1:155777124109:web:a4505d55a1f1e87bbe5244',
    messagingSenderId: '155777124109',
    projectId: 'clone-69fe9',
    authDomain: 'clone-69fe9.firebaseapp.com',
    storageBucket: 'clone-69fe9.appspot.com',
    measurementId: 'G-XK8CDVM2RV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY5I-GLCrNP-M2y7_82IuZqqX_UKHpxCs',
    appId: '1:155777124109:android:ae23ed6ff282651dbe5244',
    messagingSenderId: '155777124109',
    projectId: 'clone-69fe9',
    storageBucket: 'clone-69fe9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK89di8g0FC7AqM-IBnEK1QQ6AsTRx8iw',
    appId: '1:155777124109:ios:9dd609eb174f959fbe5244',
    messagingSenderId: '155777124109',
    projectId: 'clone-69fe9',
    storageBucket: 'clone-69fe9.appspot.com',
    iosBundleId: 'com.example.sellersApp',
  );
}
